spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: root
        password: 1234

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect

    # SQL 초기화 설정
    sql:
        init:
            mode: always  # 항상 초기화 실행
